### ISSUE TITLE
'make static' fails to compile

### ISSUE THREAD

**Issue by Mathboy19** [hammerandchisel/airhornbot#15]
When I try to 'make static' I get this error:
```
[00:16:44] Error: Cannot find module '../../audio/airhorn_default.wav'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (Constants.js:40:14)
    at Module._compile (module.js:409:26)
    at loader (C:\Users\Mathboy19\Documents\Go\go\src\github.com\hammerandchisel
\airhornbot\static\node_modules\babel-register\lib\node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Mathboy
19\Documents\Go\go\src\github.com\hammerandchisel\airhornbot\static\node_modules
\babel-register\lib\node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
make: *** [gulp] Error 1
```

And I noticed that 'airhorn_default.wav' was replaced with 'airhorn_default.dca' 
Any help would be appreciated.

**Comment by b1naryth1ef** [comment]
Fixed.
